/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#00b4c9",
        "on-surface": "#e8e5e4",
        "tertiary-fixed": "#ff9cb2",
        "on-background": "#e8e5e4",
        "on-tertiary-fixed": "#48001c",
        "inverse-surface": "#fcf8f8",
        "primary-fixed-dim": "#bba6ff",
        "surface-variant": "#262626",
        "secondary-container": "#002a30",
        "secondary": "#00daf3",
        "tertiary-container": "#ff9cb2",
        "on-primary-container": "#ffffff",
        "outline-variant": "#484848",
        "surface-container-lowest": "#000000",
        "surface-dim": "#0e0e0e",
        "secondary-fixed": "#9cf0ff",
        "on-primary-fixed": "#2d007f",
        "inverse-primary": "#6834eb",
        "background": "#0e0e0e",
        "on-tertiary-fixed-variant": "#820038",
        "on-secondary": "#004750",
        "surface-tint": "#a68cff",
        "on-primary": "#25006b",
        "on-surface-variant": "#adaaaa",
        "outline": "#767575",
        "primary-fixed": "#c8b7ff",
        "tertiary": "#ffb1c1",
        "secondary-fixed-dim": "#49e7ff",
        "error-dim": "#c94947",
        "error-container": "#8a1a1e",
        "surface-container-low": "#131313",
        "secondary-dim": "#00cbe2",
        "on-primary-fixed-variant": "#4e00cd",
        "primary": "#a68cff",
        "tertiary-fixed-dim": "#ff85a4",
        "tertiary-dim": "#ff6c95",
        "on-tertiary-container": "#720030",
        "on-error-container": "#ff9993",
        "surface-container-highest": "#262626",
        "surface-container-high": "#201f1f",
        "on-error": "#490006",
        "primary-dim": "#7e51ff",
        "on-secondary-fixed": "#00464f",
        "on-secondary-fixed-variant": "#006571",
        "surface-container": "#1a1919",
        "inverse-on-surface": "#565554",
        "on-tertiary": "#830039",
        "error": "#ff716c",
        "primary-container": "#7c4dff",
        "surface-bright": "#2c2c2c",
        "surface": "#0e0e0e"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
        "cinzel": ["Cinzel", "serif"],
        "kalam": ["Kalam", "cursive"],
        "syne": ["Syne", "sans-serif"]
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-slow': 'bounce 2s infinite',
        'pulse-fast': 'pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      }
    },
  },
  plugins: [],
}
